### ISSUE TITLE
Ingredients repo is private?

### ISSUE THREAD

**Issue by bbrala** [canonical/ubuntu-cooker#2]
I wanted to have a look how you are building the WSL apps since we kinda do the same privately for our dev env. But it seems the `git@github.com:canonical/ubuntu-cooker-ingredients` repo is not public? Is there a reason for that?

**Comment by car-meows** [comment]
Hi, 

Due to some parts of the cooker are different licensed, I am unable to be open-source all parts completely. I am currently on my week off, and I will try to make a template version of our ingredients next week so that people like can use the cooker properly.

Sorry for the inconvenience caused.

**Comment by bbrala** [comment]
Ah, no worries. The fact is in its current form this repo is kinda useless though :)

**Comment by car-meows** [comment]
Currently, I have resolved everything. You should be able to build for sideloading now.

**Comment by bbrala** [comment]
Thanks!
